#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Challenge.UI.Resource", IsApplication=true)]

namespace Challenge.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
			Challenge.Core.Resource.String.library_name = Challenge.UI.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int customer_id = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int datePicker = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int image_button = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int image_viewer = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int submit_button = 2131034116;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int enter_customer_id = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int pick_date = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int submit_button = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int take_a_picture = 2130968579;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
